<?php
/**
 * @var \Magento\Backend\Block\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "SR_ProductAttributeOptionSorting/js/option-sorting-visibility": {
                "fieldId": "sr_option_sorting_mode",
                "manualValue": "manual",
                "supportedTypes": ["select", "multiselect", "swatch_text", "swatch_visual"]
            }
        }
    }
</script>
